# Generated by Django 2.2 on 2019-05-02 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0002_noticiasmodelo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiasmodelo',
            name='tipo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticiasmodelo',
            name='detalle',
            field=models.TextField(max_length=1000),
        ),
    ]
